[[redirects]]
from = "https://get10101.finance/*"
to = "https://10101.finance"
status = 301
force = true
[[redirects]]
from = "https://www.get10101.finance/*"
to = "https://10101.finance"
status = 301
force = true
